esphome:
  name: pthc_controller
  platform: ESP32
  board: esp32dev

external_components:
  - source:
      type: git
      url: https://github.com/drakesoft/PTHC
    components: [pthc_float_output]

logger:

api:

ota:

wifi:
  ssid: "YOUR_SSID"
  password: "YOUR_PASSWORT"

output:
  - platform: pthc_float_output
    id: pthc_output
    
number:
  - platform: template
    name: pwrlvl
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    on_value:
      then:
          - lambda: !lambda |-
              ESP_LOGD("main", "Set Level: %i", x);
              id(pthc_output).set_level(x/100);   

 
